// Generated by scripts/gen-hermes-manifest.ts — do not edit by hand.
// Source: hermes-agent@4da7b9ee029c6ece2eb7992fc27dbcd086982c84
// RPC methods: 135; events: 54; commands: 95

export const HERMES_MANIFEST = {
  "provenance": {
    "sourceRevision": "4da7b9ee029c6ece2eb7992fc27dbcd086982c84",
    "sourceLabel": "hermes-agent@4da7b9ee029c6ece2eb7992fc27dbcd086982c84",
    "extractor": "scripts/gen-hermes-manifest.ts",
    "boundary": "static Python AST over explicit HERMES_AGENT_ROOT; no imports, gateway startup, HERMES_HOME reads, or producer execution",
    "inputs": [
      "hermes_cli/commands.py",
      "tools/__init__.py",
      "tools/ansi_strip.py",
      "tools/approval.py",
      "tools/async_delegation.py",
      "tools/binary_extensions.py",
      "tools/blueprints.py",
      "tools/browser_camofox.py",
      "tools/browser_camofox_state.py",
      "tools/browser_cdp_tool.py",
      "tools/browser_dialog_tool.py",
      "tools/browser_supervisor.py",
      "tools/browser_tool.py",
      "tools/budget_config.py",
      "tools/checkpoint_manager.py",
      "tools/clarify_gateway.py",
      "tools/clarify_tool.py",
      "tools/close_terminal_tool.py",
      "tools/code_execution_tool.py",
      "tools/computer_use_tool.py",
      "tools/credential_files.py",
      "tools/cronjob_tools.py",
      "tools/daemon_pool.py",
      "tools/debug_helpers.py",
      "tools/delegate_tool.py",
      "tools/delegation_live_log.py",
      "tools/desktop_ui.py",
      "tools/discord_tool.py",
      "tools/env_passthrough.py",
      "tools/env_probe.py",
      "tools/fal_common.py",
      "tools/feishu_doc_tool.py",
      "tools/feishu_drive_tool.py",
      "tools/file_operations.py",
      "tools/file_state.py",
      "tools/file_tools.py",
      "tools/focus_pane_tool.py",
      "tools/fuzzy_match.py",
      "tools/homeassistant_tool.py",
      "tools/hook_output_spill.py",
      "tools/image_generation_tool.py",
      "tools/image_source.py",
      "tools/interrupt.py",
      "tools/kanban_tools.py",
      "tools/lazy_deps.py",
      "tools/managed_tool_gateway.py",
      "tools/mcp_dashboard_oauth.py",
      "tools/mcp_oauth.py",
      "tools/mcp_oauth_manager.py",
      "tools/mcp_stdio_watchdog.py",
      "tools/mcp_tool.py",
      "tools/memory_tool.py",
      "tools/microsoft_graph_auth.py",
      "tools/microsoft_graph_client.py",
      "tools/neutts_synth.py",
      "tools/open_preview_tool.py",
      "tools/openrouter_client.py",
      "tools/osv_check.py",
      "tools/patch_parser.py",
      "tools/path_security.py",
      "tools/process_registry.py",
      "tools/project_tools.py",
      "tools/read_extract.py",
      "tools/read_terminal_tool.py",
      "tools/registry.py",
      "tools/schema_sanitizer.py",
      "tools/send_message_tool.py",
      "tools/session_search_tool.py",
      "tools/skill_manager_tool.py",
      "tools/skill_provenance.py",
      "tools/skill_usage.py",
      "tools/skills_ast_audit.py",
      "tools/skills_guard.py",
      "tools/skills_hub.py",
      "tools/skills_sync.py",
      "tools/skills_tool.py",
      "tools/slash_confirm.py",
      "tools/terminal_tool.py",
      "tools/thread_context.py",
      "tools/threat_patterns.py",
      "tools/tirith_security.py",
      "tools/todo_tool.py",
      "tools/tool_backend_helpers.py",
      "tools/tool_output_limits.py",
      "tools/tool_result_storage.py",
      "tools/tool_search.py",
      "tools/transcription_tools.py",
      "tools/tts_streaming.py",
      "tools/tts_tool.py",
      "tools/url_safety.py",
      "tools/video_generation_tool.py",
      "tools/vision_tools.py",
      "tools/voice_mode.py",
      "tools/web_tools.py",
      "tools/website_policy.py",
      "tools/working_diff.py",
      "tools/write_approval.py",
      "tools/x_search_tool.py",
      "tools/xai_http.py",
      "tools/xai_video_tools.py",
      "tools/yuanbao_tools.py",
      "tui_gateway/entry.py",
      "tui_gateway/server.py",
      "tui_gateway/ws.py"
    ]
  },
  "gateway": {
    "rpc": {
      "methods": [
        "agents.list",
        "approval.respond",
        "billing.auto_reload",
        "billing.charge",
        "billing.charge_status",
        "billing.state",
        "billing.step_up",
        "browser.manage",
        "clarify.respond",
        "cli.exec",
        "clipboard.paste",
        "command.dispatch",
        "command.resolve",
        "commands.catalog",
        "complete.path",
        "complete.slash",
        "config.get",
        "config.set",
        "config.show",
        "cron.manage",
        "delegation.pause",
        "delegation.status",
        "file.attach",
        "handoff.fail",
        "handoff.request",
        "handoff.state",
        "image.attach",
        "image.attach_bytes",
        "image.detach",
        "input.detect_drop",
        "insights.get",
        "learning.delete",
        "learning.detail",
        "learning.edit",
        "learning.frames",
        "llm.oneshot",
        "model.disconnect",
        "model.options",
        "model.save_key",
        "paste.collapse",
        "pdf.attach",
        "pet.cancel",
        "pet.cells",
        "pet.disable",
        "pet.export",
        "pet.gallery",
        "pet.generate",
        "pet.generate.status",
        "pet.hatch",
        "pet.info",
        "pet.info.meta",
        "pet.remove",
        "pet.rename",
        "pet.scale",
        "pet.select",
        "pet.thumb",
        "plugins.list",
        "plugins.manage",
        "preview.restart",
        "process.kill",
        "process.list",
        "process.stop",
        "project.facts",
        "projects.add_folder",
        "projects.archive",
        "projects.create",
        "projects.delete",
        "projects.discover_repos",
        "projects.for_cwd",
        "projects.get",
        "projects.list",
        "projects.project_sessions",
        "projects.record_repos",
        "projects.remove_folder",
        "projects.set_active",
        "projects.set_primary",
        "projects.tree",
        "projects.update",
        "prompt.background",
        "prompt.submit",
        "reload.env",
        "reload.mcp",
        "rollback.diff",
        "rollback.list",
        "rollback.restore",
        "secret.respond",
        "session.activate",
        "session.active_list",
        "session.branch",
        "session.close",
        "session.compress",
        "session.context_breakdown",
        "session.create",
        "session.cwd.set",
        "session.delete",
        "session.history",
        "session.interrupt",
        "session.list",
        "session.most_recent",
        "session.redirect",
        "session.resume",
        "session.save",
        "session.status",
        "session.steer",
        "session.title",
        "session.undo",
        "session.usage",
        "setup.runtime_check",
        "setup.status",
        "shell.exec",
        "skills.manage",
        "skills.reload",
        "slash.exec",
        "spawn_tree.list",
        "spawn_tree.load",
        "spawn_tree.save",
        "subagent.interrupt",
        "subscription.change",
        "subscription.preview",
        "subscription.resume",
        "subscription.state",
        "subscription.upgrade",
        "sudo.respond",
        "system.battery",
        "terminal.read.respond",
        "terminal.resize",
        "tools.configure",
        "tools.list",
        "tools.show",
        "toolsets.list",
        "usage.bars",
        "verification.status",
        "voice.record",
        "voice.toggle",
        "voice.tts"
      ],
      "sourceFile": "tui_gateway/server.py",
      "sources": {
        "agents.list": {
          "line": 18312,
          "kind": "decorator"
        },
        "approval.respond": {
          "line": 13215,
          "kind": "decorator"
        },
        "billing.auto_reload": {
          "line": 9869,
          "kind": "decorator"
        },
        "billing.charge": {
          "line": 9814,
          "kind": "decorator"
        },
        "billing.charge_status": {
          "line": 9840,
          "kind": "decorator"
        },
        "billing.state": {
          "line": 9535,
          "kind": "decorator"
        },
        "billing.step_up": {
          "line": 9891,
          "kind": "decorator"
        },
        "browser.manage": {
          "line": 17901,
          "kind": "decorator"
        },
        "clarify.respond": {
          "line": 13187,
          "kind": "decorator"
        },
        "cli.exec": {
          "line": 15277,
          "kind": "decorator"
        },
        "clipboard.paste": {
          "line": 12394,
          "kind": "decorator"
        },
        "command.dispatch": {
          "line": 15348,
          "kind": "decorator"
        },
        "command.resolve": {
          "line": 15318,
          "kind": "decorator"
        },
        "commands.catalog": {
          "line": 15155,
          "kind": "decorator"
        },
        "complete.path": {
          "line": 16211,
          "kind": "decorator"
        },
        "complete.slash": {
          "line": 16479,
          "kind": "decorator"
        },
        "config.get": {
          "line": 14526,
          "kind": "decorator"
        },
        "config.set": {
          "line": 13240,
          "kind": "decorator"
        },
        "config.show": {
          "line": 18100,
          "kind": "decorator"
        },
        "cron.manage": {
          "line": 18336,
          "kind": "decorator"
        },
        "delegation.pause": {
          "line": 10546,
          "kind": "decorator"
        },
        "delegation.status": {
          "line": 10526,
          "kind": "decorator"
        },
        "file.attach": {
          "line": 12897,
          "kind": "decorator"
        },
        "handoff.fail": {
          "line": 8303,
          "kind": "decorator"
        },
        "handoff.request": {
          "line": 8188,
          "kind": "decorator"
        },
        "handoff.state": {
          "line": 8276,
          "kind": "decorator"
        },
        "image.attach": {
          "line": 12434,
          "kind": "decorator"
        },
        "image.attach_bytes": {
          "line": 12566,
          "kind": "decorator"
        },
        "image.detach": {
          "line": 12944,
          "kind": "decorator"
        },
        "input.detect_drop": {
          "line": 12964,
          "kind": "decorator"
        },
        "insights.get": {
          "line": 17671,
          "kind": "decorator"
        },
        "learning.delete": {
          "line": 18398,
          "kind": "decorator"
        },
        "learning.detail": {
          "line": 18387,
          "kind": "decorator"
        },
        "learning.edit": {
          "line": 18409,
          "kind": "decorator"
        },
        "learning.frames": {
          "line": 18363,
          "kind": "decorator"
        },
        "llm.oneshot": {
          "line": 8129,
          "kind": "decorator"
        },
        "model.disconnect": {
          "line": 16712,
          "kind": "decorator"
        },
        "model.options": {
          "line": 16609,
          "kind": "decorator"
        },
        "model.save_key": {
          "line": 16632,
          "kind": "decorator"
        },
        "paste.collapse": {
          "line": 15982,
          "kind": "decorator"
        },
        "pdf.attach": {
          "line": 12627,
          "kind": "decorator"
        },
        "pet.cancel": {
          "line": 9106,
          "kind": "decorator"
        },
        "pet.cells": {
          "line": 8613,
          "kind": "decorator"
        },
        "pet.disable": {
          "line": 8958,
          "kind": "decorator"
        },
        "pet.export": {
          "line": 8858,
          "kind": "decorator"
        },
        "pet.gallery": {
          "line": 8718,
          "kind": "decorator"
        },
        "pet.generate": {
          "line": 9151,
          "kind": "decorator"
        },
        "pet.generate.status": {
          "line": 9120,
          "kind": "decorator"
        },
        "pet.hatch": {
          "line": 9264,
          "kind": "decorator"
        },
        "pet.info": {
          "line": 8564,
          "kind": "decorator"
        },
        "pet.info.meta": {
          "line": 8590,
          "kind": "decorator"
        },
        "pet.remove": {
          "line": 8828,
          "kind": "decorator"
        },
        "pet.rename": {
          "line": 8885,
          "kind": "decorator"
        },
        "pet.scale": {
          "line": 8972,
          "kind": "decorator"
        },
        "pet.select": {
          "line": 8801,
          "kind": "decorator"
        },
        "pet.thumb": {
          "line": 8923,
          "kind": "decorator"
        },
        "plugins.list": {
          "line": 18078,
          "kind": "decorator"
        },
        "plugins.manage": {
          "line": 18504,
          "kind": "decorator"
        },
        "preview.restart": {
          "line": 13057,
          "kind": "decorator"
        },
        "process.kill": {
          "line": 14852,
          "kind": "decorator"
        },
        "process.list": {
          "line": 14840,
          "kind": "decorator"
        },
        "process.stop": {
          "line": 14813,
          "kind": "decorator"
        },
        "project.facts": {
          "line": 7109,
          "kind": "decorator"
        },
        "projects.add_folder": {
          "line": 14010,
          "kind": "projects-wrapper"
        },
        "projects.archive": {
          "line": 14037,
          "kind": "projects-wrapper"
        },
        "projects.create": {
          "line": 13976,
          "kind": "projects-wrapper"
        },
        "projects.delete": {
          "line": 14044,
          "kind": "projects-wrapper"
        },
        "projects.discover_repos": {
          "line": 14247,
          "kind": "decorator"
        },
        "projects.for_cwd": {
          "line": 14057,
          "kind": "projects-wrapper"
        },
        "projects.get": {
          "line": 13971,
          "kind": "projects-wrapper"
        },
        "projects.list": {
          "line": 13966,
          "kind": "projects-wrapper"
        },
        "projects.project_sessions": {
          "line": 14500,
          "kind": "decorator"
        },
        "projects.record_repos": {
          "line": 14272,
          "kind": "decorator"
        },
        "projects.remove_folder": {
          "line": 14023,
          "kind": "projects-wrapper"
        },
        "projects.set_active": {
          "line": 14051,
          "kind": "projects-wrapper"
        },
        "projects.set_primary": {
          "line": 14030,
          "kind": "projects-wrapper"
        },
        "projects.tree": {
          "line": 14473,
          "kind": "decorator"
        },
        "projects.update": {
          "line": 13995,
          "kind": "projects-wrapper"
        },
        "prompt.background": {
          "line": 13011,
          "kind": "decorator"
        },
        "prompt.submit": {
          "line": 10829,
          "kind": "decorator"
        },
        "reload.env": {
          "line": 15088,
          "kind": "decorator"
        },
        "reload.mcp": {
          "line": 14938,
          "kind": "decorator"
        },
        "rollback.diff": {
          "line": 17776,
          "kind": "decorator"
        },
        "rollback.list": {
          "line": 17699,
          "kind": "decorator"
        },
        "rollback.restore": {
          "line": 17729,
          "kind": "decorator"
        },
        "secret.respond": {
          "line": 13210,
          "kind": "decorator"
        },
        "session.activate": {
          "line": 7951,
          "kind": "decorator"
        },
        "session.active_list": {
          "line": 7913,
          "kind": "decorator"
        },
        "session.branch": {
          "line": 10316,
          "kind": "decorator"
        },
        "session.close": {
          "line": 10304,
          "kind": "decorator"
        },
        "session.compress": {
          "line": 10060,
          "kind": "decorator"
        },
        "session.context_breakdown": {
          "line": 8351,
          "kind": "decorator"
        },
        "session.create": {
          "line": 6857,
          "kind": "decorator"
        },
        "session.cwd.set": {
          "line": 7671,
          "kind": "decorator"
        },
        "session.delete": {
          "line": 7975,
          "kind": "decorator"
        },
        "session.history": {
          "line": 10008,
          "kind": "decorator"
        },
        "session.interrupt": {
          "line": 10452,
          "kind": "decorator"
        },
        "session.list": {
          "line": 7009,
          "kind": "decorator"
        },
        "session.most_recent": {
          "line": 7060,
          "kind": "decorator"
        },
        "session.redirect": {
          "line": 10778,
          "kind": "decorator"
        },
        "session.resume": {
          "line": 7263,
          "kind": "decorator"
        },
        "session.save": {
          "line": 10232,
          "kind": "decorator"
        },
        "session.status": {
          "line": 9932,
          "kind": "decorator"
        },
        "session.steer": {
          "line": 10745,
          "kind": "decorator"
        },
        "session.title": {
          "line": 8025,
          "kind": "decorator"
        },
        "session.undo": {
          "line": 10032,
          "kind": "decorator"
        },
        "session.usage": {
          "line": 8327,
          "kind": "decorator"
        },
        "setup.runtime_check": {
          "line": 14715,
          "kind": "decorator"
        },
        "setup.status": {
          "line": 14705,
          "kind": "decorator"
        },
        "shell.exec": {
          "line": 18583,
          "kind": "decorator"
        },
        "skills.manage": {
          "line": 18420,
          "kind": "decorator"
        },
        "skills.reload": {
          "line": 18479,
          "kind": "decorator"
        },
        "slash.exec": {
          "line": 17163,
          "kind": "decorator"
        },
        "spawn_tree.list": {
          "line": 10670,
          "kind": "decorator"
        },
        "spawn_tree.load": {
          "line": 10721,
          "kind": "decorator"
        },
        "spawn_tree.save": {
          "line": 10627,
          "kind": "decorator"
        },
        "subagent.interrupt": {
          "line": 10554,
          "kind": "decorator"
        },
        "subscription.change": {
          "line": 9734,
          "kind": "decorator"
        },
        "subscription.preview": {
          "line": 9709,
          "kind": "decorator"
        },
        "subscription.resume": {
          "line": 9757,
          "kind": "decorator"
        },
        "subscription.state": {
          "line": 9675,
          "kind": "decorator"
        },
        "subscription.upgrade": {
          "line": 9775,
          "kind": "decorator"
        },
        "sudo.respond": {
          "line": 13205,
          "kind": "decorator"
        },
        "system.battery": {
          "line": 14788,
          "kind": "decorator"
        },
        "terminal.read.respond": {
          "line": 13196,
          "kind": "decorator"
        },
        "terminal.resize": {
          "line": 10817,
          "kind": "decorator"
        },
        "tools.configure": {
          "line": 18213,
          "kind": "decorator"
        },
        "tools.list": {
          "line": 18139,
          "kind": "decorator"
        },
        "tools.show": {
          "line": 18170,
          "kind": "decorator"
        },
        "toolsets.list": {
          "line": 18282,
          "kind": "decorator"
        },
        "usage.bars": {
          "line": 9600,
          "kind": "decorator"
        },
        "verification.status": {
          "line": 7128,
          "kind": "decorator"
        },
        "voice.record": {
          "line": 17575,
          "kind": "decorator"
        },
        "voice.toggle": {
          "line": 17474,
          "kind": "decorator"
        },
        "voice.tts": {
          "line": 17652,
          "kind": "decorator"
        }
      },
      "diff": {
        "additions": [
          "approval.respond",
          "billing.auto_reload",
          "billing.charge",
          "billing.charge_status",
          "billing.state",
          "billing.step_up",
          "clarify.respond",
          "command.resolve",
          "config.show",
          "file.attach",
          "handoff.fail",
          "handoff.request",
          "handoff.state",
          "image.attach_bytes",
          "insights.get",
          "llm.oneshot",
          "model.disconnect",
          "pdf.attach",
          "pet.cancel",
          "pet.cells",
          "pet.disable",
          "pet.export",
          "pet.gallery",
          "pet.generate",
          "pet.generate.status",
          "pet.hatch",
          "pet.info",
          "pet.info.meta",
          "pet.remove",
          "pet.rename",
          "pet.scale",
          "pet.select",
          "pet.thumb",
          "plugins.list",
          "plugins.manage",
          "preview.restart",
          "process.kill",
          "process.list",
          "process.stop",
          "project.facts",
          "projects.add_folder",
          "projects.archive",
          "projects.create",
          "projects.delete",
          "projects.discover_repos",
          "projects.for_cwd",
          "projects.get",
          "projects.list",
          "projects.project_sessions",
          "projects.record_repos",
          "projects.remove_folder",
          "projects.set_active",
          "projects.set_primary",
          "projects.tree",
          "projects.update",
          "secret.respond",
          "session.cwd.set",
          "session.most_recent",
          "session.redirect",
          "session.status",
          "setup.runtime_check",
          "setup.status",
          "subscription.change",
          "subscription.preview",
          "subscription.resume",
          "subscription.state",
          "subscription.upgrade",
          "sudo.respond",
          "system.battery",
          "terminal.read.respond",
          "terminal.resize",
          "tools.list",
          "tools.show",
          "usage.bars",
          "verification.status",
          "voice.record",
          "voice.toggle",
          "voice.tts"
        ],
        "removals": [
          "client.capabilities"
        ],
        "likelyRenames": []
      }
    },
    "events": {
      "names": [
        "agent.terminal.output",
        "approval.request",
        "background.complete",
        "billing.step_up.verification",
        "browser.progress",
        "clarify.expire",
        "clarify.request",
        "error",
        "gateway.ready",
        "message.complete",
        "message.delta",
        "message.interim",
        "message.start",
        "moa.aggregating",
        "moa.phase",
        "moa.progress",
        "moa.reference",
        "notification.clear",
        "notification.show",
        "pane.reveal",
        "pet.generate.progress",
        "pet.hatch.progress",
        "preview.open",
        "preview.restart.complete",
        "preview.restart.progress",
        "reaction",
        "reasoning.available",
        "reasoning.delta",
        "review.summary",
        "secret.expire",
        "secret.request",
        "session.info",
        "session.title",
        "skin.changed",
        "status.update",
        "subagent.complete",
        "subagent.progress",
        "subagent.spawn_requested",
        "subagent.start",
        "subagent.thinking",
        "subagent.tool",
        "sudo.expire",
        "sudo.request",
        "terminal.close",
        "terminal.read.expire",
        "terminal.read.request",
        "thinking.delta",
        "tool.complete",
        "tool.generating",
        "tool.output_risk",
        "tool.start",
        "voice.interrupted",
        "voice.status",
        "voice.transcript"
      ],
      "sources": {
        "agent.terminal.output": [
          {
            "path": "tui_gateway/server.py",
            "line": 11629,
            "kind": "_emit"
          }
        ],
        "approval.request": [
          {
            "path": "tui_gateway/server.py",
            "line": 1543,
            "kind": "_emit"
          }
        ],
        "background.complete": [
          {
            "path": "tui_gateway/server.py",
            "line": 13031,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13044,
            "kind": "_emit"
          }
        ],
        "billing.step_up.verification": [
          {
            "path": "tui_gateway/server.py",
            "line": 9910,
            "kind": "_emit"
          }
        ],
        "browser.progress": [
          {
            "path": "tui_gateway/server.py",
            "line": 17941,
            "kind": "_emit"
          }
        ],
        "clarify.expire": [
          {
            "path": "tui_gateway/server.py",
            "line": 5038,
            "kind": "derived-expire"
          }
        ],
        "clarify.request": [
          {
            "path": "tui_gateway/server.py",
            "line": 5038,
            "kind": "_block"
          }
        ],
        "error": [
          {
            "path": "tui_gateway/server.py",
            "line": 1975,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4000,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 6758,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 10991,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11786,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 12257,
            "kind": "_emit"
          }
        ],
        "gateway.ready": [
          {
            "path": "tui_gateway/entry.py",
            "line": 443,
            "kind": "jsonrpc-event-frame"
          },
          {
            "path": "tui_gateway/ws.py",
            "line": 307,
            "kind": "jsonrpc-event-frame"
          }
        ],
        "message.complete": [
          {
            "path": "tui_gateway/server.py",
            "line": 1469,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4991,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 6835,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 12083,
            "kind": "_emit"
          }
        ],
        "message.delta": [
          {
            "path": "tui_gateway/server.py",
            "line": 4968,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4973,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11880,
            "kind": "_emit"
          }
        ],
        "message.interim": [
          {
            "path": "tui_gateway/server.py",
            "line": 5070,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11889,
            "kind": "_emit"
          }
        ],
        "message.start": [
          {
            "path": "tui_gateway/server.py",
            "line": 4959,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 6587,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11383,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11469,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11547,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11703,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 12323,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 12369,
            "kind": "_emit"
          }
        ],
        "moa.aggregating": [
          {
            "path": "tui_gateway/server.py",
            "line": 4803,
            "kind": "_emit"
          }
        ],
        "moa.phase": [
          {
            "path": "tui_gateway/server.py",
            "line": 4840,
            "kind": "_emit"
          }
        ],
        "moa.progress": [
          {
            "path": "tui_gateway/server.py",
            "line": 4813,
            "kind": "_emit"
          }
        ],
        "moa.reference": [
          {
            "path": "tui_gateway/server.py",
            "line": 4800,
            "kind": "_emit"
          }
        ],
        "notification.clear": [
          {
            "path": "tui_gateway/server.py",
            "line": 1797,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5035,
            "kind": "_emit"
          }
        ],
        "notification.show": [
          {
            "path": "tui_gateway/server.py",
            "line": 1780,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5023,
            "kind": "_emit"
          }
        ],
        "pane.reveal": [
          {
            "path": "tools/focus_pane_tool.py",
            "line": 26,
            "kind": "desktop_ui.emit"
          }
        ],
        "pet.generate.progress": [
          {
            "path": "tui_gateway/server.py",
            "line": 9212,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 9228,
            "kind": "_emit"
          }
        ],
        "pet.hatch.progress": [
          {
            "path": "tui_gateway/server.py",
            "line": 9324,
            "kind": "_emit"
          }
        ],
        "preview.open": [
          {
            "path": "tools/open_preview_tool.py",
            "line": 46,
            "kind": "desktop_ui.emit"
          }
        ],
        "preview.restart.complete": [
          {
            "path": "tui_gateway/server.py",
            "line": 13149,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13151,
            "kind": "_emit"
          }
        ],
        "preview.restart.progress": [
          {
            "path": "tui_gateway/server.py",
            "line": 5457,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13131,
            "kind": "_emit"
          }
        ],
        "reaction": [
          {
            "path": "tui_gateway/server.py",
            "line": 5011,
            "kind": "_emit"
          }
        ],
        "reasoning.available": [
          {
            "path": "tui_gateway/server.py",
            "line": 4785,
            "kind": "_emit"
          }
        ],
        "reasoning.delta": [
          {
            "path": "tui_gateway/server.py",
            "line": 4962,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5012,
            "kind": "_emit"
          }
        ],
        "review.summary": [
          {
            "path": "tui_gateway/server.py",
            "line": 1942,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5948,
            "kind": "_emit"
          }
        ],
        "secret.expire": [
          {
            "path": "tui_gateway/server.py",
            "line": 5151,
            "kind": "derived-expire"
          }
        ],
        "secret.request": [
          {
            "path": "tui_gateway/server.py",
            "line": 5151,
            "kind": "_block"
          }
        ],
        "session.info": [
          {
            "path": "tui_gateway/server.py",
            "line": 1476,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 1967,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 2279,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 3923,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4551,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5134,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5269,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5520,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5591,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 5964,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 7691,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 10184,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 10979,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13388,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13506,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13554,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13568,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13686,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 15016,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 15939,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 17119,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 17141,
            "kind": "_emit"
          }
        ],
        "session.title": [
          {
            "path": "tui_gateway/server.py",
            "line": 12198,
            "kind": "_emit"
          }
        ],
        "skin.changed": [
          {
            "path": "tui_gateway/server.py",
            "line": 2903,
            "kind": "_broadcast_global_event"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 13891,
            "kind": "_broadcast_global_event"
          }
        ],
        "status.update": [
          {
            "path": "tui_gateway/server.py",
            "line": 1559,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 6582,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11368,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11444,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 11530,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 12121,
            "kind": "_emit"
          }
        ],
        "subagent.complete": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1049,
            "kind": "delegate-tool"
          },
          {
            "path": "tools/delegate_tool.py",
            "line": 2238,
            "kind": "delegate-tool"
          },
          {
            "path": "tools/delegate_tool.py",
            "line": 2507,
            "kind": "delegate-tool"
          },
          {
            "path": "tools/delegate_tool.py",
            "line": 2518,
            "kind": "delegate-tool"
          }
        ],
        "subagent.progress": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1140,
            "kind": "delegate-tool"
          },
          {
            "path": "tools/delegate_tool.py",
            "line": 1147,
            "kind": "delegate-tool"
          }
        ],
        "subagent.spawn_requested": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1590,
            "kind": "delegate-tool"
          }
        ],
        "subagent.start": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1045,
            "kind": "delegate-tool"
          },
          {
            "path": "tools/delegate_tool.py",
            "line": 2114,
            "kind": "delegate-tool"
          }
        ],
        "subagent.thinking": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1083,
            "kind": "delegate-tool"
          }
        ],
        "subagent.tool": [
          {
            "path": "tools/delegate_tool.py",
            "line": 1136,
            "kind": "delegate-tool"
          }
        ],
        "sudo.expire": [
          {
            "path": "tui_gateway/server.py",
            "line": 5144,
            "kind": "derived-expire"
          }
        ],
        "sudo.request": [
          {
            "path": "tui_gateway/server.py",
            "line": 5144,
            "kind": "_block"
          }
        ],
        "terminal.close": [
          {
            "path": "tui_gateway/server.py",
            "line": 11639,
            "kind": "_emit"
          }
        ],
        "terminal.read.expire": [
          {
            "path": "tui_gateway/server.py",
            "line": 5055,
            "kind": "derived-expire"
          }
        ],
        "terminal.read.request": [
          {
            "path": "tui_gateway/server.py",
            "line": 5055,
            "kind": "_block"
          }
        ],
        "thinking.delta": [
          {
            "path": "tui_gateway/server.py",
            "line": 5008,
            "kind": "_emit"
          }
        ],
        "tool.complete": [
          {
            "path": "tui_gateway/server.py",
            "line": 4750,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4976,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4989,
            "kind": "_emit"
          }
        ],
        "tool.generating": [
          {
            "path": "tui_gateway/server.py",
            "line": 5007,
            "kind": "_emit"
          }
        ],
        "tool.output_risk": [
          {
            "path": "tui_gateway/server.py",
            "line": 4779,
            "kind": "_emit"
          }
        ],
        "tool.start": [
          {
            "path": "tui_gateway/server.py",
            "line": 4703,
            "kind": "_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 4986,
            "kind": "_emit"
          }
        ],
        "voice.interrupted": [
          {
            "path": "tui_gateway/server.py",
            "line": 17426,
            "kind": "_voice_emit"
          }
        ],
        "voice.status": [
          {
            "path": "tui_gateway/server.py",
            "line": 17623,
            "kind": "_voice_emit"
          }
        ],
        "voice.transcript": [
          {
            "path": "tui_gateway/server.py",
            "line": 17439,
            "kind": "_voice_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 17622,
            "kind": "_voice_emit"
          },
          {
            "path": "tui_gateway/server.py",
            "line": 17624,
            "kind": "_voice_emit"
          }
        ]
      },
      "coveredDynamicSources": [
        {
          "call": "_emit",
          "line": 4903,
          "path": "tui_gateway/server.py",
          "rule": "delegate-subagent-relay"
        },
        {
          "call": "_emit",
          "line": 11665,
          "path": "tui_gateway/server.py",
          "rule": "delegate-subagent-relay"
        }
      ],
      "diff": {
        "additions": [
          "clarify.expire",
          "pane.reveal",
          "preview.open",
          "secret.expire",
          "subagent.spawn_requested",
          "sudo.expire",
          "terminal.read.expire"
        ],
        "removals": [
          "btw.complete",
          "gateway.protocol_error",
          "gateway.start_timeout",
          "gateway.stderr",
          "tool.progress"
        ],
        "likelyRenames": []
      }
    }
  },
  "session": {
    "keys": [
      "model",
      "provider",
      "reasoning_effort",
      "service_tier",
      "fast",
      "yolo",
      "approval_mode",
      "tools",
      "skills",
      "cwd",
      "branch",
      "project",
      "personality",
      "running",
      "title",
      "stored_session_id",
      "desktop_contract",
      "version",
      "release_date",
      "update_behind",
      "update_command",
      "usage",
      "profile_name",
      "mcp_servers",
      "system_prompt",
      "credential_warning"
    ],
    "desktopContract": 4
  },
  "commands": {
    "slash-dynamic:quick_commands": {"description":"Profile quick commands discovered at runtime by commands.catalog.","kind":"slash-dynamic","name":"quick_commands","source":"tui_gateway/server.py:dynamic"},
    "slash-dynamic:skills": {"description":"Skill commands discovered at runtime by commands.catalog.","kind":"slash-dynamic","name":"skills","source":"tui_gateway/server.py:dynamic"},
    "slash-extra:density": {"aliases":[],"argsHint":"","category":"TUI","cliOnly":false,"description":"Toggle compact display mode","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash-extra","name":"density","source":"tui_gateway/server.py:15119","subcommands":[],"tuiExtra":true},
    "slash-extra:logs": {"aliases":[],"argsHint":"","category":"TUI","cliOnly":false,"description":"Show recent gateway log lines","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash-extra","name":"logs","source":"tui_gateway/server.py:15120","subcommands":[],"tuiExtra":true},
    "slash-extra:mouse": {"aliases":[],"argsHint":"","category":"TUI","cliOnly":false,"description":"Set mouse tracking preset [on|off|toggle|wheel|buttons|all]","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash-extra","name":"mouse","source":"tui_gateway/server.py:15121","subcommands":[],"tuiExtra":true},
    "slash-extra:sessions": {"aliases":[],"argsHint":"","category":"TUI","cliOnly":false,"description":"Switch between live TUI sessions","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash-extra","name":"sessions","source":"tui_gateway/server.py:15126","subcommands":[],"tuiExtra":true},
    "slash:agents": {"aliases":["tasks"],"argsHint":"","category":"Session","cliOnly":false,"description":"Show active agents and running tasks","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"agents","source":"hermes_cli/commands.py:104","subcommands":[]},
    "slash:approvals": {"aliases":[],"argsHint":"[manual|smart|off]","category":"Configuration","cliOnly":false,"description":"Show or set the persistent dangerous-command approval mode","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"approvals","source":"hermes_cli/commands.py:168","subcommands":["manual","smart","off"]},
    "slash:approve": {"aliases":[],"argsHint":"[session|always]","category":"Session","cliOnly":false,"description":"Approve a pending dangerous command","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"approve","source":"hermes_cli/commands.py:98","subcommands":[]},
    "slash:background": {"aliases":["bg","btw"],"argsHint":"<prompt>","category":"Session","cliOnly":false,"description":"Run a prompt in the background","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"background","source":"hermes_cli/commands.py:102","subcommands":[]},
    "slash:battery": {"aliases":[],"argsHint":"[on|off|status]","category":"Configuration","cliOnly":true,"description":"Toggle a color-coded battery indicator in the status bar","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"battery","source":"hermes_cli/commands.py:148","subcommands":["on","off","status"]},
    "slash:blueprint": {"aliases":["bp"],"argsHint":"[name] [slot=value ...]","category":"Tools & Skills","cliOnly":false,"description":"Set up an automation from a blueprint template","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"blueprint","source":"hermes_cli/commands.py:218","subcommands":[]},
    "slash:branch": {"aliases":["fork"],"argsHint":"[name]","category":"Session","cliOnly":false,"description":"Branch the current session (explore a different path)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"branch","source":"hermes_cli/commands.py:89","subcommands":[]},
    "slash:browser": {"aliases":[],"argsHint":"[connect|disconnect|status]","category":"Tools & Skills","cliOnly":true,"description":"Connect browser tools to your live Chromium-family browser via CDP","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"browser","source":"hermes_cli/commands.py:237","subcommands":["connect","disconnect","status"]},
    "slash:bundles": {"aliases":[],"argsHint":"","category":"Tools & Skills","cliOnly":false,"description":"List skill bundles (aliases /<name> for multiple skills)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"bundles","source":"hermes_cli/commands.py:202","subcommands":[]},
    "slash:busy": {"aliases":[],"argsHint":"[queue|steer|interrupt|status]","category":"Configuration","cliOnly":true,"description":"Control what Enter does while Hermes is working","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"busy","source":"hermes_cli/commands.py:184","subcommands":["queue","steer","interrupt","status"]},
    "slash:clear": {"aliases":[],"argsHint":"","category":"Session","cliOnly":true,"description":"Clear screen and start a new session","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"clear","source":"hermes_cli/commands.py:72","subcommands":[]},
    "slash:codex-runtime": {"aliases":["codex_runtime"],"argsHint":"[auto|codex_app_server]","category":"Configuration","cliOnly":false,"description":"Toggle codex app-server runtime for OpenAI/Codex models","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"codex-runtime","source":"hermes_cli/commands.py:140","subcommands":[]},
    "slash:commands": {"aliases":[],"argsHint":"[page]","category":"Info","cliOnly":false,"description":"Browse all commands and skills (paginated)","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"commands","source":"hermes_cli/commands.py:244","subcommands":[]},
    "slash:compress": {"aliases":["compact"],"argsHint":"[here [N] | focus topic | --preview|--dry-run]","category":"Session","cliOnly":false,"description":"Compress conversation context (add 'here [N]' to keep recent N turns; --preview shows what would happen)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"compress","source":"hermes_cli/commands.py:91","subcommands":[]},
    "slash:config": {"aliases":[],"argsHint":"","category":"Configuration","cliOnly":true,"description":"Show current configuration","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"config","source":"hermes_cli/commands.py:136","subcommands":[]},
    "slash:context": {"aliases":["ctx"],"argsHint":"[all]","category":"Session","cliOnly":false,"description":"Show detailed context window view with usage gauge, category breakdown, compression stats, and throughput","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"context","source":"hermes_cli/commands.py:123","subcommands":["all"]},
    "slash:copy": {"aliases":[],"argsHint":"[number]","category":"Info","cliOnly":true,"description":"Copy the last assistant response to clipboard","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"copy","source":"hermes_cli/commands.py:260","subcommands":[]},
    "slash:cron": {"aliases":[],"argsHint":"[subcommand]","category":"Tools & Skills","cliOnly":true,"description":"Manage scheduled tasks","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"cron","source":"hermes_cli/commands.py:212","subcommands":["list","add","create","edit","pause","resume","run","remove"]},
    "slash:curator": {"aliases":[],"argsHint":"[subcommand]","category":"Tools & Skills","cliOnly":false,"description":"Background skill maintenance (status, run, pin, archive, list-archived)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"curator","source":"hermes_cli/commands.py:220","subcommands":["status","run","pause","resume","pin","unpin","restore","list-archived"]},
    "slash:debug": {"aliases":[],"argsHint":"[nous|local]","category":"Info","cliOnly":false,"description":"Upload debug report (system info + logs) and get shareable links","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"debug","source":"hermes_cli/commands.py:268","subcommands":[]},
    "slash:deny": {"aliases":[],"argsHint":"[all] [reason]","category":"Session","cliOnly":false,"description":"Deny a pending dangerous command (optionally with a reason)","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"deny","source":"hermes_cli/commands.py:100","subcommands":[]},
    "slash:diff": {"aliases":[],"argsHint":"[staged|all|session] [--stat] [path...]","category":"Info","cliOnly":false,"description":"Show git changes in the working directory","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"diff","source":"hermes_cli/commands.py:154","subcommands":["staged","all","session"]},
    "slash:egress": {"aliases":[],"argsHint":"[status]","category":"Session","cliOnly":false,"description":"Show Docker egress proxy status","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"egress","source":"hermes_cli/commands.py:121","subcommands":["status"]},
    "slash:fast": {"aliases":[],"argsHint":"[normal|fast|status] [--global]","category":"Configuration","cliOnly":false,"description":"Toggle fast mode — OpenAI Priority Processing / Anthropic Fast Mode (Normal/Fast)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"fast","source":"hermes_cli/commands.py:174","subcommands":["normal","fast","status","on","off","--global"]},
    "slash:focus": {"aliases":[],"argsHint":"[on|off|status]","category":"Configuration","cliOnly":true,"description":"Toggle focus view — show only your prompt and the final response","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"focus","source":"hermes_cli/commands.py:160","subcommands":["on","off","status"]},
    "slash:footer": {"aliases":[],"argsHint":"[on|off|status]","category":"Configuration","cliOnly":false,"description":"Toggle gateway runtime-metadata footer on final replies","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"footer","source":"hermes_cli/commands.py:163","subcommands":["on","off","status"]},
    "slash:goal": {"aliases":[],"argsHint":"[text | draft <text> | show | pause | resume | clear | status | wait <pid> | unwait]","category":"Session","cliOnly":false,"description":"Set a standing goal Hermes works on across turns until achieved","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"goal","source":"hermes_cli/commands.py:114","subcommands":[]},
    "slash:handoff": {"aliases":[],"argsHint":"<platform>","category":"Session","cliOnly":true,"description":"Hand off this session to a messaging platform (Telegram, Discord, etc.)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"handoff","source":"hermes_cli/commands.py:87","subcommands":[]},
    "slash:hatch": {"aliases":["generate-pet"],"argsHint":"[description]","category":"Tools & Skills","cliOnly":true,"description":"Generate a new petdex pet from a description","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"hatch","source":"hermes_cli/commands.py:206","subcommands":[]},
    "slash:help": {"aliases":[],"argsHint":"","category":"Info","cliOnly":false,"description":"Show available commands","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"help","source":"hermes_cli/commands.py:246","subcommands":[]},
    "slash:history": {"aliases":[],"argsHint":"","category":"Session","cliOnly":true,"description":"Show conversation history","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"history","source":"hermes_cli/commands.py:76","subcommands":[]},
    "slash:image": {"aliases":[],"argsHint":"<path>","category":"Info","cliOnly":true,"description":"Attach a local image file for your next prompt","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"image","source":"hermes_cli/commands.py:264","subcommands":[]},
    "slash:indicator": {"aliases":[],"argsHint":"[kaomoji|emoji|unicode|ascii]","category":"Configuration","cliOnly":true,"description":"Pick the TUI busy-indicator style","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"indicator","source":"hermes_cli/commands.py:179","subcommands":["kaomoji","emoji","unicode","ascii"]},
    "slash:init": {"aliases":[],"argsHint":"[notes]","category":"Tools & Skills","cliOnly":false,"description":"Generate or update AGENTS.md project instructions from a repo scan","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"init","source":"hermes_cli/commands.py:210","subcommands":[]},
    "slash:insights": {"aliases":[],"argsHint":"[days]","category":"Info","cliOnly":false,"description":"Show usage insights and analytics","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"insights","source":"hermes_cli/commands.py:254","subcommands":[]},
    "slash:journey": {"aliases":["learning","memory-graph"],"argsHint":"[list|delete <id>|edit <id>]","category":"Session","cliOnly":true,"description":"Open the learning journey timeline","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"journey","source":"hermes_cli/commands.py:106","subcommands":["list","delete","edit"]},
    "slash:kanban": {"aliases":[],"argsHint":"[subcommand]","category":"Tools & Skills","cliOnly":false,"description":"Multi-profile collaboration board (tasks, links, comments)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"kanban","source":"hermes_cli/commands.py:223","subcommands":["init","boards","create","list","ls","show","assign","reclaim","reassign","diagnostics","diag","link","unlink","claim","comment","complete","edit","block","unblock","archive","tail","dispatch","stats","notify-subscribe","notify-list","notify-unsubscribe","log","runs","heartbeat","assignees","context","specify","gc"]},
    "slash:learn": {"aliases":[],"argsHint":"<what to learn from>","category":"Tools & Skills","cliOnly":false,"description":"Learn a reusable skill from anything you describe (dirs, URLs, this chat, notes)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"learn","source":"hermes_cli/commands.py:208","subcommands":[]},
    "slash:memory": {"aliases":[],"argsHint":"[pending|approve|reject|approval] [id|on|off]","category":"Tools & Skills","cliOnly":false,"description":"Review pending memory writes / toggle the approval gate","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"memory","source":"hermes_cli/commands.py:198","subcommands":["pending","approve","reject","approval"]},
    "slash:moa": {"aliases":[],"argsHint":"<prompt>","category":"Session","cliOnly":false,"description":"Run one prompt through the default Mixture of Agents preset, then restore your model","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"moa","source":"hermes_cli/commands.py:116","subcommands":[]},
    "slash:model": {"aliases":[],"argsHint":"[model] [--provider name] [--global|--session] [--refresh]","category":"Configuration","cliOnly":false,"description":"Switch model (session-scoped; --global to persist)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"model","source":"hermes_cli/commands.py:138","subcommands":[]},
    "slash:new": {"aliases":["reset"],"argsHint":"[name]","category":"Session","cliOnly":false,"description":"Start a new session (fresh session ID + history)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"new","source":"hermes_cli/commands.py:68","subcommands":[]},
    "slash:paste": {"aliases":[],"argsHint":"","category":"Info","cliOnly":true,"description":"Attach clipboard image from your clipboard","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"paste","source":"hermes_cli/commands.py:262","subcommands":[]},
    "slash:personality": {"aliases":[],"argsHint":"[name]","category":"Configuration","cliOnly":false,"description":"Set a predefined personality","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"personality","source":"hermes_cli/commands.py:144","subcommands":[]},
    "slash:pet": {"aliases":[],"argsHint":"[toggle|list|scale <n>|<slug>]","category":"Tools & Skills","cliOnly":true,"description":"Toggle or adopt a petdex mascot (/pet, /pet list, /pet <slug>)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"pet","source":"hermes_cli/commands.py:204","subcommands":["toggle","list","scale","off"]},
    "slash:platform": {"aliases":[],"argsHint":"<pause|resume|list> [name]","category":"Info","cliOnly":false,"description":"Pause, resume, or list a failing gateway platform","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"platform","source":"hermes_cli/commands.py:258","subcommands":[]},
    "slash:platforms": {"aliases":["gateway"],"argsHint":"","category":"Info","cliOnly":true,"description":"Show gateway/messaging platform status","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"platforms","source":"hermes_cli/commands.py:256","subcommands":[]},
    "slash:plugins": {"aliases":[],"argsHint":"","category":"Tools & Skills","cliOnly":true,"description":"List installed plugins and their status","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"plugins","source":"hermes_cli/commands.py:240","subcommands":[]},
    "slash:profile": {"aliases":[],"argsHint":"","category":"Info","cliOnly":false,"description":"Show active profile name and home directory","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"profile","source":"hermes_cli/commands.py:126","subcommands":[]},
    "slash:prompt": {"aliases":["compose"],"argsHint":"[initial text]","category":"Session","cliOnly":true,"description":"Compose your next prompt in $EDITOR (markdown), then send it","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"prompt","source":"hermes_cli/commands.py:81","subcommands":[]},
    "slash:queue": {"aliases":["q"],"argsHint":"<prompt>","category":"Session","cliOnly":false,"description":"Queue a prompt for the next turn (doesn't interrupt)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"queue","source":"hermes_cli/commands.py:110","subcommands":[]},
    "slash:quit": {"aliases":["exit"],"argsHint":"[--delete]","category":"Exit","cliOnly":true,"description":"Exit the CLI (use --delete to also remove session history)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"quit","source":"hermes_cli/commands.py:272","subcommands":[]},
    "slash:reasoning": {"aliases":[],"argsHint":"[level|show|hide|full|clamp] [--global]","category":"Configuration","cliOnly":false,"description":"Manage reasoning effort and display","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"reasoning","source":"hermes_cli/commands.py:171","subcommands":["none","minimal","low","medium","high","xhigh","max","ultra","show","hide","on","off","full","clamp","--global"]},
    "slash:redraw": {"aliases":[],"argsHint":"","category":"Session","cliOnly":true,"description":"Force a full UI repaint (recovers from terminal drift)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"redraw","source":"hermes_cli/commands.py:74","subcommands":[]},
    "slash:reload": {"aliases":[],"argsHint":"","category":"Tools & Skills","cliOnly":true,"description":"Reload .env variables into the running session","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"reload","source":"hermes_cli/commands.py:231","subcommands":[]},
    "slash:reload-mcp": {"aliases":["reload_mcp"],"argsHint":"","category":"Tools & Skills","cliOnly":false,"description":"Reload MCP servers from config","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"reload-mcp","source":"hermes_cli/commands.py:233","subcommands":[]},
    "slash:reload-skills": {"aliases":["reload_skills"],"argsHint":"","category":"Tools & Skills","cliOnly":false,"description":"Re-scan ~/.hermes/skills/ for newly installed or removed skills","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"reload-skills","source":"hermes_cli/commands.py:235","subcommands":[]},
    "slash:restart": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Gracefully restart the gateway after draining active runs","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"restart","source":"hermes_cli/commands.py:247","subcommands":[]},
    "slash:resume": {"aliases":[],"argsHint":"[name]","category":"Session","cliOnly":false,"description":"Resume a previously-named session","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"resume","source":"hermes_cli/commands.py:129","subcommands":[]},
    "slash:retry": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Retry the last message (resend to agent)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"retry","source":"hermes_cli/commands.py:80","subcommands":[]},
    "slash:rollback": {"aliases":[],"argsHint":"[number]","category":"Session","cliOnly":false,"description":"List or restore filesystem checkpoints","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"rollback","source":"hermes_cli/commands.py:93","subcommands":[]},
    "slash:save": {"aliases":[],"argsHint":"","category":"Session","cliOnly":true,"description":"Save the current conversation","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"save","source":"hermes_cli/commands.py:78","subcommands":[]},
    "slash:sessions": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Browse and resume previous sessions","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"sessions","source":"hermes_cli/commands.py:133","subcommands":[]},
    "slash:sethome": {"aliases":["set-home"],"argsHint":"","category":"Session","cliOnly":false,"description":"Set this chat as the home channel","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"sethome","source":"hermes_cli/commands.py:127","subcommands":[]},
    "slash:skills": {"aliases":[],"argsHint":"","category":"Tools & Skills","cliOnly":true,"description":"Search, install, inspect, or manage skills","gatewayConfigGate":"skills.write_approval","gatewayOnly":false,"kind":"slash","name":"skills","source":"hermes_cli/commands.py:193","subcommands":["search","browse","inspect","install","audit","pending","approve","reject","diff","approval"]},
    "slash:skin": {"aliases":[],"argsHint":"[name]","category":"Configuration","cliOnly":true,"description":"Show or change the display skin/theme","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"skin","source":"hermes_cli/commands.py:177","subcommands":[]},
    "slash:snapshot": {"aliases":["snap"],"argsHint":"[create|restore <id>|prune]","category":"Session","cliOnly":true,"description":"Create or restore state snapshots of Hermes config/state","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"snapshot","source":"hermes_cli/commands.py:95","subcommands":[]},
    "slash:start": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Acknowledge platform start pings without a reply","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"start","source":"hermes_cli/commands.py:66","subcommands":[]},
    "slash:status": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Show session, model, token, and context info","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"status","source":"hermes_cli/commands.py:120","subcommands":[]},
    "slash:statusbar": {"aliases":["sb"],"argsHint":"","category":"Configuration","cliOnly":true,"description":"Toggle the context/model status bar","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"statusbar","source":"hermes_cli/commands.py:146","subcommands":[]},
    "slash:steer": {"aliases":[],"argsHint":"<prompt>","category":"Session","cliOnly":false,"description":"Inject a message after the next tool call without interrupting","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"steer","source":"hermes_cli/commands.py:112","subcommands":[]},
    "slash:stop": {"aliases":[],"argsHint":"","category":"Session","cliOnly":false,"description":"Kill all running background processes","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"stop","source":"hermes_cli/commands.py:97","subcommands":[]},
    "slash:subgoal": {"aliases":[],"argsHint":"[text | remove N | clear]","category":"Session","cliOnly":false,"description":"Add or manage extra criteria on the active goal","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"subgoal","source":"hermes_cli/commands.py:118","subcommands":[]},
    "slash:subscription": {"aliases":["upgrade"],"argsHint":"","category":"Info","cliOnly":true,"description":"View your Nous plan and change it in the browser","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"subscription","source":"hermes_cli/commands.py:251","subcommands":[]},
    "slash:suggestions": {"aliases":["suggest"],"argsHint":"[accept|dismiss N | catalog]","category":"Tools & Skills","cliOnly":false,"description":"Review suggested automations (accept/dismiss)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"suggestions","source":"hermes_cli/commands.py:215","subcommands":["accept","dismiss","catalog","clear"]},
    "slash:timestamps": {"aliases":["ts"],"argsHint":"[on|off|status]","category":"Configuration","cliOnly":true,"description":"Toggle [HH:MM] timestamps on messages and /history","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"timestamps","source":"hermes_cli/commands.py:151","subcommands":["on","off","status"]},
    "slash:title": {"aliases":[],"argsHint":"[name]","category":"Session","cliOnly":false,"description":"Set a title for the current session","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"title","source":"hermes_cli/commands.py:85","subcommands":[]},
    "slash:tools": {"aliases":[],"argsHint":"[list|disable|enable] [name...]","category":"Tools & Skills","cliOnly":true,"description":"Manage tools: /tools [list|disable|enable] [name...]","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"tools","source":"hermes_cli/commands.py:189","subcommands":[]},
    "slash:toolsets": {"aliases":[],"argsHint":"","category":"Tools & Skills","cliOnly":true,"description":"List available toolsets","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"toolsets","source":"hermes_cli/commands.py:191","subcommands":[]},
    "slash:topic": {"aliases":[],"argsHint":"[off|help|session-id]","category":"Session","cliOnly":false,"description":"Enable or inspect Telegram DM topic sessions","gatewayConfigGate":null,"gatewayOnly":true,"kind":"slash","name":"topic","source":"hermes_cli/commands.py:70","subcommands":[]},
    "slash:topup": {"aliases":[],"argsHint":"","category":"Info","cliOnly":false,"description":"Show your Nous balance and manage billing on the portal","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"topup","source":"hermes_cli/commands.py:253","subcommands":[]},
    "slash:undo": {"aliases":[],"argsHint":"[N]","category":"Session","cliOnly":false,"description":"Back up N user turns and re-prompt (default 1)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"undo","source":"hermes_cli/commands.py:83","subcommands":[]},
    "slash:update": {"aliases":[],"argsHint":"","category":"Info","cliOnly":false,"description":"Update Hermes Agent to the latest version","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"update","source":"hermes_cli/commands.py:266","subcommands":[]},
    "slash:usage": {"aliases":[],"argsHint":"[reset [--force]]","category":"Info","cliOnly":false,"description":"Show token usage and rate limits; `reset` redeems a banked Codex limit reset","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"usage","source":"hermes_cli/commands.py:249","subcommands":[]},
    "slash:verbose": {"aliases":[],"argsHint":"","category":"Configuration","cliOnly":true,"description":"Cycle tool progress display: off -> new -> all -> verbose -> log","gatewayConfigGate":"display.tool_progress_command","gatewayOnly":false,"kind":"slash","name":"verbose","source":"hermes_cli/commands.py:157","subcommands":[]},
    "slash:version": {"aliases":["v"],"argsHint":"","category":"Info","cliOnly":false,"description":"Show Hermes Agent version","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"version","source":"hermes_cli/commands.py:267","subcommands":[]},
    "slash:voice": {"aliases":[],"argsHint":"[on|off|tts|status]","category":"Configuration","cliOnly":false,"description":"Toggle voice mode","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"voice","source":"hermes_cli/commands.py:182","subcommands":["on","off","tts","status"]},
    "slash:whoami": {"aliases":[],"argsHint":"","category":"Info","cliOnly":false,"description":"Show your slash command access (admin / user)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"whoami","source":"hermes_cli/commands.py:125","subcommands":[]},
    "slash:yolo": {"aliases":[],"argsHint":"","category":"Configuration","cliOnly":false,"description":"Toggle YOLO mode (skip all dangerous command approvals)","gatewayConfigGate":null,"gatewayOnly":false,"kind":"slash","name":"yolo","source":"hermes_cli/commands.py:166","subcommands":[]},
  }
} as const

export type ProducerId = `rpc:${typeof HERMES_MANIFEST.gateway.rpc.methods[number]}` | keyof typeof HERMES_MANIFEST.commands
